version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:12.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery_bd
    ports:
      - "5433:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ytkaev12@live.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"